sudo: false
language: elixir
elixir: 
  - 1.4.0
otp_release:
  - 19.1
notifications:
  recipients:
    - adam@apathydrive.com
after_success:
  - "mix compile && mix coveralls.travis"
env:
  - MIX_ENV=test
